name: Gitea
run-name: Test
on:
  push:
  workflow_dispatch:

jobs:
  Explore-Gitea-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt-openj9' # See 'Supported distributions' for available options
          java-version: '21'
