name: Build Minecraft Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create build directory
        run: |
          New-Item -Path build -ItemType Directory -Force

      - name: Download Minecraft JAR
        run: |
          Invoke-WebRequest -Uri "https://github.com/fxlgm/j9build/releases/download/nead/1.16.5-Forge.jar" -OutFile "build/1.16.5-Forge.jar"

      - name: Verify jpackage installation
        run: |
          jpackage --version

      - name: Build Executable
        run: |
          jpackage --input build --name Minecraft --main-jar 1.16.5-Forge.jar --main-class net.minecraft.client.Minecraft --type exe --dest build --verbose

      - name: List build directory
        run: |
          Get-ChildItem -Path build

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: minecraft-executable
          path: build/Minecraft.exe
