name: Build Minecraft Launcher

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Minecraft Files
      run: Invoke-WebRequest -Uri "https://github.com/fxlgm/j9build/releases/download/Neadnew/mc.zip" -OutFile "mc.zip"

    - name: Extract Minecraft Files
      run: Expand-Archive -Path "mc.zip" -DestinationPath "build" -Force

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Executable with jpackage
      run: |
        jpackage --input build --name Minecraft --main-jar 1.16.5-Forge.jar --main-class net.minecraft.client.Minecraft --type exe --dest build

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: minecraft-executable
        path: build/Minecraft.exe
